In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:

df = pd.read_csv(r'C:\Users\kalpe\Downloads\airline_passenger_satisfaction.csv')

In [3]:
df.head()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,3,5,2,5,5,5,3,5,5,Neutral or Dissatisfied
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,5,4,5,5,3,5,2,5,5,Satisfied
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,3,5,3,5,5,3,4,3,3,Satisfied
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,5,5,5,4,4,5,2,5,5,Satisfied
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,3,4,4,5,4,3,3,3,3,Satisfied

In [4]:
df = df.drop(['ID', 'Departure and Arrival Time Convenience', 'Gender'], axis=1)

In [5]:
df.isnull().sum()
df.head()

,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Ease of Online Booking,Check-in Service,Online Boarding,...,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction
0,48,First-time,Business,Business,821,2,5.0,3,4,3,...,3,5,2,5,5,5,3,5,5,Neutral or Dissatisfied
1,35,Returning,Business,Business,821,26,39.0,2,3,5,...,5,4,5,5,3,5,2,5,5,Satisfied
2,41,Returning,Business,Business,853,0,0.0,4,4,5,...,3,5,3,5,5,3,4,3,3,Satisfied
3,50,Returning,Business,Business,1905,0,0.0,2,3,4,...,5,5,5,4,4,5,2,5,5,Satisfied
4,49,Returning,Business,Business,3470,0,1.0,3,3,5,...,3,4,4,5,4,3,3,3,3,Satisfied

In [6]:
from sklearn.impute import SimpleImputer
num_imputer = SimpleImputer(strategy='mean')
df['Arrival Delay'] = num_imputer.fit_transform(df[['Arrival Delay']])

In [7]:
df.isnull().sum()

Age                        0
Customer Type              0
Type of Travel             0
Class                      0
Flight Distance            0
Departure Delay            0
Arrival Delay              0
Ease of Online Booking     0
Check-in Service           0
Online Boarding            0
Gate Location              0
On-board Service           0
Seat Comfort               0
Leg Room Service           0
Cleanliness                0
Food and Drink             0
In-flight Service          0
In-flight Wifi Service     0
In-flight Entertainment    0
Baggage Handling           0
Satisfaction               0
dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [9]:
df['Customer Type'] = encoder.fit_transform(df['Customer Type'])
df['Type of Travel'] = encoder.fit_transform(df['Type of Travel'])
df['Class'] = encoder.fit_transform(df['Class'])
df['Satisfaction'] = encoder.fit_transform(df['Satisfaction'])

In [10]:
df.head()

,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Ease of Online Booking,Check-in Service,Online Boarding,...,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction
0,48,0,0,0,821,2,5.0,3,4,3,...,3,5,2,5,5,5,3,5,5,0
1,35,1,0,0,821,26,39.0,2,3,5,...,5,4,5,5,3,5,2,5,5,1
2,41,1,0,0,853,0,0.0,4,4,5,...,3,5,3,5,5,3,4,3,3,1
3,50,1,0,0,1905,0,0.0,2,3,4,...,5,5,5,4,4,5,2,5,5,1
4,49,1,0,0,3470,0,1.0,3,3,5,...,3,4,4,5,4,3,3,3,3,1

In [11]:
df['Flight Distance'].max()

4983

In [12]:
X=df.drop(['Satisfaction'],axis=1)
Y=df['Satisfaction']

In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [14]:
# use logistic regression 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [15]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, Y_train)

C:\Users\kalpe\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [16]:
y_pred = model.predict(X_test)

In [17]:
accuracy = accuracy_score(Y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.86

In [18]:
cm = confusion_matrix(Y_test, y_pred)
print('Confusion Matrix:')
print(cm)

Confusion Matrix:
[[12872  1851]
 [ 1869  9384]]

In [19]:
report = classification_report(Y_test, y_pred)
print('Classification Report:')
print(report)

Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.87      0.87     14723
           1       0.84      0.83      0.83     11253

    accuracy                           0.86     25976
   macro avg       0.85      0.85      0.85     25976
weighted avg       0.86      0.86      0.86     25976

In [20]:
# use svm to train the model
from sklearn.svm import SVC

In [ ]:
model2=SVC(kernel='rbf')
model2.fit(X_train, Y_train)

In [ ]:
y2_pred=model2.predict(X_test)

In [ ]:
accuracy2=accuracy_score(Y_test,y2_pred)
print(f'Accuracy2: {accuracy2:.2f}')